# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- tonychue-patch-1

parameters:
  - name: environment
    type: string
    default: 'dev'
    values:
    - dev
    - stage
    - prod
  - name: serviceConnection
    type: string
    default: 'terraform'
  # - name: stateKey
  #   type: string
  #   default: ''
  - name: workingDirectory
    type: string
    default: '$(System.DefaultWorkingDirectory)'

pool:
  vmImage: ubuntu-latest

stages:

- stage: Plan_${{ parameters.environment }}
  displayName: Plan_${{ parameters.environment }}

  jobs:
  - job: TerraformPlan

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      displayName: 'Azure Login and Terraform Init'
      inputs:
        azureSubscription: 'terraform'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        inlineScript: |
          set -e

          echo "Azure account:"
          az account show

          echo "Subscription:"
          az account show --query id -o tsv
          az storage blob list \
            --account-name tfdevopsaccount \
            --container-name tf-dev-state-container \
            --auth-mode login \
            --output table

          az account show \
          --query "{appId:user.name, subscription:id, tenant:tenantId}" \
          -o table
          # terraform init 
          # # \
            # -backend-config="storage_account_name=tfdevopsaccount" \
            # -backend-config="container_name=tf-dev-state-container" \
            # -backend-config="key=uksouth/terraform.state" \
            # -backend-config="resource_group_name=rg_devops" \
            # -backend-config="subscription_id=732ec2db-5140-4675-bf72-0dd352a999a8" \
            # -backend-config="use_azuread_auth=true"
    - task: TerraformTask@5
      displayName: 'Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: ${{ parameters.workingDirectory }}
        backendServiceArm: ${{ parameters.serviceConnection }}
        backendAzureRmResourceGroupName: 'rg_devops'
        backendAzureRmStorageAccountName: 'tfdevopsaccount'
        backendAzureRmContainerName: 'tf-dev-state-container'
        backendAzureRmKey: uksouth/${{ parameters.environment }}/terraform.tfstate
        backendAzureRmUseCliFlagsForAuthentication: true

    - task: TerraformTask@5
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-out=tfplan -var-file=${{ parameters.workingDirectory }}/environments/${{ parameters.environment }}.tfvars'
        workingDirectory: ${{ parameters.workingDirectory }}
        environmentServiceNameAzureRM: ${{ parameters.serviceConnection }}
        # publishPlan: 'Production plan'

    - publish: ${{ parameters.workingDirectory }}/tfplan
      artifact: plan-${{ parameters.environment }}

- stage: Apply_${{ parameters.environment }} 
  displayName: Apply_${{ parameters.environment }}
  dependsOn: Plan_${{ parameters.environment }}
  jobs:
    - deployment: TerraformApply
      displayName: 'Terraform Apply'
      environment: ${{ parameters.environment }}
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: TerraformInstaller@1
              displayName: 'Install Terraform'
              inputs:
                terraformVersion: 'latest'
            - download: current
              artifact: plan-${{ parameters.environment }}  
              # path: ${{ parameters.workingDirectory }}
            - task: TerraformTask@5
              displayName: 'Terraform Init'
              inputs:
                provider: 'azurerm'
                command: 'init'
                workingDirectory: ${{ parameters.workingDirectory }}
                backendServiceArm: ${{ parameters.serviceConnection }}
                backendAzureRmResourceGroupName: 'rg_devops'
                backendAzureRmStorageAccountName: 'tfdevopsaccount'
                backendAzureRmContainerName: 'tf-dev-state-container'
                backendAzureRmKey: uksouth/${{ parameters.environment }}/terraform.tfstate
                backendAzureRmUseCliFlagsForAuthentication: true
            # - task: TerraformTask@5
            #   displayName: 'Apply Terraform Plan'
            #   # condition: and(succeeded(), eq(variables['terraformPlan.changesPresent'], 'true'))
            #   inputs:
            #     provider: 'azurerm'
            #     command: 'apply'
            #     commandOptions: 'tfplan'
            #     workingDirectory: ${{ parameters.workingDirectory }}
            #     environmentServiceNameAzureRM: ${{ parameters.serviceConnection }}
