# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
    - tonychue-patch-1

parameters:
  - name: environment
    type: string
    default: 'dev'
    values:
    - dev
    - stage
    - prod
  - name: serviceConnection
    type: string
    default: 'terraform'
  - name: stateKey
    type: string
    default: uksouth/dev/terraform.tfstate
  - name: workingDirectory
    type: string
    default: '$(System.DefaultWorkingDirectory)'
  - name: destroy
    type: boolean
    default: false
  - name: confirmDestroy
    type: string
    default: ''
pool:
  vmImage: ubuntu-latest

stages:

- stage: Plan_${{ parameters.environment }}
  displayName: Plan_${{ parameters.environment }}

  jobs:
  - job: TerraformPlan

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      displayName: 'Azure Login and Terraform Init'
      inputs:
        azureSubscription: ${{ parameters.serviceConnection }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        workingDirectory: ${{ parameters.workingDirectory }}
        inlineScript: |
          set -e

          echo "Azure account:"
          az account show

          echo "Subscription:"
          az account show --query id -o tsv
          az storage blob list \
            --account-name tfdevopsaccount \
            --container-name tf-dev-state-container \
            --auth-mode login \
            --output table

          az account show \
          --query "{appId:user.name, subscription:id, tenant:tenantId}" \
          -o table
          # terraform init 
          # # \
            # -backend-config="storage_account_name=tfdevopsaccount" \
            # -backend-config="container_name=tf-dev-state-container" \
            # -backend-config="key=uksouth/terraform.state" \
            # -backend-config="resource_group_name=rg_devops" \
            # -backend-config="subscription_id=732ec2db-5140-4675-bf72-0dd352a999a8" \
            # -backend-config="use_azuread_auth=true"
    - task: TerraformTask@5
      displayName: 'Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: ${{ parameters.workingDirectory }}
        backendServiceArm: ${{ parameters.serviceConnection }}
        backendAzureRmResourceGroupName: 'rg_devops'
        backendAzureRmStorageAccountName: 'tfdevopsaccount'
        backendAzureRmContainerName: 'tf-dev-state-container'
        backendAzureRmKey: uksouth/${{ parameters.environment }}/terraform.tfstate
        backendAzureRmUseCliFlagsForAuthentication: false

    # - task: TerraformTask@5
    #   displayName: 'Terraform Plan'
    #   inputs:
    #     provider: 'azurerm'
    #     command: 'plan'
    #     commandOptions: '-out=tfplan -var-file=${{ parameters.workingDirectory }}/environments/${{ parameters.environment }}.tfvars'
    #     workingDirectory: ${{ parameters.workingDirectory }}
    #     environmentServiceNameAzureRM: ${{ parameters.serviceConnection }}


    - task: AzureCLI@2
      name: terraformPlan
      displayName: 'Terraform Plan'
      inputs:
        azureSubscription: ${{ parameters.serviceConnection }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        addSpnToEnvironment: true
        workingDirectory: ${{ parameters.workingDirectory }}

        inlineScript: |
          set +e

          echo "Azure account:"
          az account show

          echo "Subscription:"
          az account show --query id -o tsv

          echo "Tenant:"
          az account show --query tenantId -o tsv

          terraform plan \
            -out=tfplan \
            -detailed-exitcode \
            -var-file="${{ parameters.workingDirectory }}/environments/${{ parameters.environment }}.tfvars"

          PLAN_EXIT_CODE=$?

          echo "Terraform plan exit code: $PLAN_EXIT_CODE"

          if [ "$PLAN_EXIT_CODE" -eq 0 ]; then

            echo "No infrastructure changes detected."

            echo "##vso[task.setvariable variable=changesPresent;isOutput=true]false"

          elif [ "$PLAN_EXIT_CODE" -eq 2 ]; then

            echo "Infrastructure changes detected."

            echo "##vso[task.setvariable variable=changesPresent;isOutput=true]true"

          else

            echo "Terraform plan failed."

            exit "$PLAN_EXIT_CODE"

          fi

    - publish: ${{ parameters.workingDirectory }}/tfplan
      artifact: plan-${{ parameters.environment }}
    - bash: |
        echo "changesPresent = '$(terraformPlan.changesPresent)'"
      displayName: Debug Terraform Change Status

- stage: Apply_${{ parameters.environment }} 
  displayName: Apply_${{ parameters.environment }}
  dependsOn: Plan_${{ parameters.environment }}
  variables:
    changesPresent: $[stageDependencies.Plan_${{ parameters.environment }}.TerraformPlan.outputs['terraformPlan.changesPresent']]
    condition: and(succeeded(),eq(variables['changesPresent'], 'true'),eq('${{ parameters.destroy }}', 'false'))
  jobs:
    - deployment: TerraformApply
      displayName: 'Terraform Apply'
      environment: ${{ parameters.environment }}
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: TerraformInstaller@1
              displayName: 'Install Terraform'
              inputs:
                terraformVersion: 'latest'
            - download: current
              artifact: plan-${{ parameters.environment }}  
              # path: ${{ parameters.workingDirectory }}
            - task: TerraformTask@5
              displayName: 'Terraform Init'
              inputs:
                provider: 'azurerm'
                command: 'init'
                workingDirectory: ${{ parameters.workingDirectory }}
                backendServiceArm: ${{ parameters.serviceConnection }}
                backendAzureRmResourceGroupName: 'rg_devops'
                backendAzureRmStorageAccountName: 'tfdevopsaccount'
                backendAzureRmContainerName: 'tf-dev-state-container'
                backendAzureRmKey: uksouth/${{ parameters.environment }}/terraform.tfstate
                backendAzureRmUseCliFlagsForAuthentication: true
            - bash: |
                echo "changesPresent = '$(changesPresent)'"
              displayName: Debug Terraform Change Status
            - task: TerraformTask@5
              displayName: 'Apply Terraform Plan'
              # condition: and(succeeded(), eq(variables['terraformPlan.changesPresent'], 'true'))
              inputs:
                provider: 'azurerm'
                command: 'apply'
                commandOptions: $(Pipeline.Workspace)/plan-${{ parameters.environment }}/tfplan
                workingDirectory: ${{ parameters.workingDirectory }}
                environmentServiceNameAzureRM: ${{ parameters.serviceConnection }}

- stage: Destroy_${{ parameters.environment }}
  displayName: Destroy ${{ parameters.environment }}

  dependsOn:
    - Plan_${{ parameters.environment }}

  condition: >
    and(
      succeeded(),
      eq('${{ parameters.destroy }}', 'true'),
      or(
        ne('${{ parameters.environment }}', 'prod'),
        eq('${{ parameters.confirmDestroy }}', 'DESTROY-PROD')
      )
    )

  jobs:

  - deployment: TerraformDestroy
    displayName: Terraform Destroy

    environment: ${{ parameters.environment }}

    strategy:
      runOnce:
        deploy:

          steps:

          - checkout: self

          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: latest

          - task: TerraformTask@5
            displayName: Terraform Init
            inputs:
              provider: azurerm
              command: init
              workingDirectory: ${{ parameters.workingDirectory }}
              backendServiceArm: ${{ parameters.serviceConnection }}
              backendAzureRmResourceGroupName: rg_devops
              backendAzureRmStorageAccountName: tfdevopsaccount
              backendAzureRmContainerName: tf-dev-state-container
              backendAzureRmKey: uksouth/${{ parameters.environment }}/terraform.tfstate
              backendAzureRmUseCliFlagsForAuthentication: true

          - task: TerraformTask@5
            displayName: Terraform Destroy
            inputs:
              provider: azurerm
              command: destroy
              workingDirectory: ${{ parameters.workingDirectory }}
              environmentServiceNameAzureRM: ${{ parameters.serviceConnection }}
              commandOptions: >
                -var-file=${{ parameters.workingDirectory }}/environments/${{ parameters.environment }}.tfvars
                -auto-approve